export const TRAITS = [
  'Energetic',
  'Lazy',
  'Chaotic',
  'Friendly',
  'Smart',
  'Genius',
  'Gremlin',
  'Drama queen',
  'Professional sleeper',
  'Snack addict',
  'Overthinker',
  'Goblin',
  'Emotionally unavailable',
  'Certified good boy',
  'Dictator',
  'Main character',
  'Side quest enjoyer',
  'Suspicious',
  'Too powerful',
  'Cursed',
  'Blessed',
  'Silly',
  'Existential',
  'Absolutely unhinged',
  'Chaos engine',
  'Tired',
  'Manipulative',
  'Mystical',
  'Hyperactive',
  'Introvert',
  'Extrovert',
  'Therapist',
  'Conspiracy theorist',
  'Gym bro',
  'Pirate',
  'Peasant',
  'Cute',
  'Villain',
  'NPC',
  'Average',
  'Elegant',
  'Feral',
  'Shakespearean',
  'Wizard',
  'Time traveler',
  'Crypto enthusiast',
  'Floppy',
  'Philosopher',
  'Clingy',
]

export const MAX_TRAITS = 5

export const HOROSCOPES = [
  'Aries',
  'Taurus',
  'Gemini',
  'Cancer',
  'Leo',
  'Virgo',
  'Libra',
  'Scorpio',
  'Sagittarius',
  'Capricorn',
  'Aquarius',
  'Pisces',
]
