services:
  client:
    image: create-a-dog-client-dev
    build:
      context: ./client
      dockerfile: dev.Dockerfile
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - VITE_BACKEND_URL=/api

  server:
    image: create-a-dog-server-dev
    build:
      context: ./server
      dockerfile: dev.Dockerfile
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules

  nginx:
    image: nginx
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    depends_on:
      - client
      - server
